{
 "title": "Room status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Humidity (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temperature_c" }
   ]
  },
  {
   "title": "CO2 Concentration (ppm)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "co2_concentration" }
   ]
  }
 ]
}