{
 "title": "Estado",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "co2_concentration{instance=\"192.168.1.6:9000\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "temperature_c{instance=\"192.168.1.6:9000\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "humidity{instance=\"192.168.1.6:9000\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "co2_concentration{instance=\"192.168.1.7:9000\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "temperature_c{instance=\"192.168.1.7:9000\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "humidity{instance=\"192.168.1.6:9000\"}"
    }
   ]
  },
  {
   "title": "Humedad (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "humidity{instance=\"192.168.1.6:9000\"}"
    }
   ]
  },
  {
   "title": "Humedad (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "humidity{instance=\"192.168.1.7:9000\"}"
    }
   ]
  },
  {
   "title": "Temperatura (C)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "temperature_c{instance=\"192.168.1.6:9000\"}"
    }
   ]
  },
  {
   "title": "Temperatura (C)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "temperature_c{instance=\"192.168.1.7:9000\"}"
    }
   ]
  },
  {
   "title": "Dioxido de carbono (ppm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "co2_concentration{instance=\"192.168.1.6:9000\"}"
    }
   ]
  },
  {
   "title": "Dioxido de carbono (ppm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "co2_concentration{instance=\"192.168.1.7:9000\"}"
    }
   ]
  }
 ]
}